# This file is generated by scripts/export_abacus_fixtures.py.
# Abacus root: /home/user/Documents/GITHUB/tandpds/abacus
# Abacus revision: 9a0bfe5da32e2465e8804cd16817e8737af100fd (dirty)
const ABACUS_CALIBRATION_UNALIGNED_CASES = [
    (
        name = "reports_unaligned_rows",
        coords = (; channel = [1, 2, 3], geo = String["A", "B", "C"]),
        df = (; channel = [1000, 2], geo = String["A", "Z"]),
        expected_unaligned_1based = Dict{String, Vector{Int}}("channel" => [1], "geo" => [2]),
    ),
]
