# This file is generated by scripts/export_abacus_fixtures.py.
# Abacus root: /home/user/Documents/GITHUB/tandpds/abacus
# Abacus revision: 9a0bfe5da32e2465e8804cd16817e8737af100fd (dirty)
const ABACUS_CALIBRATION_ALIGNMENT_CASES = [
    (
        name = "matches_model_coords",
        coords = (; channel = [1, 2, 3], geo = String["A", "B", "C"]),
        df = (; channel = [1, 2], geo = String["A", "C"]),
        expected_indices_1based = Dict{String, Vector{Int}}("channel" => [1, 2], "geo" => [1, 3]),
    ),
    (
        name = "single_dim_channel_only",
        coords = (; channel = [1, 2, 3]),
        df = (; channel = [3, 1]),
        expected_indices_1based = Dict{String, Vector{Int}}("channel" => [3, 1]),
    ),
]
