# This file is generated by scripts/export_abacus_fixtures.py.
# Abacus root: /home/user/Documents/GITHUB/tandpds/abacus
# Abacus revision: 9a0bfe5da32e2465e8804cd16817e8737af100fd (dirty)
const ABACUS_CALIBRATION_CHANNEL_SCALING_CASES = [
    (
        name = "sparse_channel_rows",
        channel_columns = String["organic", "paid", "social"],
        scale = Float64[1.0, 2.0, 3.0],
        df = (; channel = String["organic", "organic", "social"], x = Float64[1.0, 2.0, 3.0], delta_x = Float64[1.0, 1.0, 1.0]),
        expected = (; channel = String["organic", "organic", "social"], x = Float64[1.0, 2.0, 9.0], delta_x = Float64[1.0, 1.0, 3.0]),
    ),
]
