# This file is generated by scripts/export_abacus_fixtures.py.
# Abacus root: /home/user/Documents/GITHUB/tandpds/abacus
# Abacus revision: 9a0bfe5da32e2465e8804cd16817e8737af100fd (dirty)
const ABACUS_CALIBRATION_MONOTONIC_CASES = [
    (
        name = "monotonic_increasing",
        delta_x = Float64[1.0, 2.0, 3.0],
        delta_y = Float64[0.5, 1.0, 1.5],
        expect_error = false,
    ),
    (
        name = "monotonic_zero_delta_x",
        delta_x = Float64[0.0, 2.0],
        delta_y = Float64[0.0, 1.0],
        expect_error = false,
    ),
    (
        name = "non_monotonic_conflicting_sign",
        delta_x = Float64[1.0, 2.0, 3.0],
        delta_y = Float64[1.0, -2.0, 3.0],
        expect_error = true,
    ),
]
