# This file is generated by scripts/export_abacus_fixtures.py.
# Abacus root: /home/user/Documents/GITHUB/tandpds/abacus
# Abacus revision: 9a0bfe5da32e2465e8804cd16817e8737af100fd (dirty)
const ABACUS_CALIBRATION_TARGET_SCALING_CASES = [
    (
        name = "rescale_series",
        target = Float64[0.0, 3.0, 6.0, 9.0],
        scale = 3.0,
        expected = Float64[0.0, 1.0, 2.0, 3.0],
    ),
]
