# This file is generated by scripts/export_abacus_fixtures.py.
# Abacus root: /home/user/Documents/GITHUB/tandpds/abacus
# Abacus revision: 7fd0ef30aacc33c97342d21087c3f3653bb8a74c (dirty)
const ABACUS_CALIBRATION_INTEGRATION_CASES = [
    (
        name = "timeseries_logistic_lift_and_cost_per_target",
        channel_columns = String["tv", "search"],
        channel_scale = Float64[4.0, 3.0],
        target_scale = 11.5,
        lam = Float64[0.6, 0.7],
        lift = (; channel = String["tv", "search"], x = Float64[1.0, 0.5], delta_x = Float64[0.5, 0.25], delta_y = Float64[0.3, 0.15], sigma = Float64[0.1, 0.05]),
        cost_per_target = (; gathered_cpt = Float64[0.5, 0.8], targets = Float64[0.45, 0.7], sigma = Float64[0.1, 0.2]),
        expected_lift_payload = (
            channel_index = [1, 2],
            x = Float64[0.25, 0.16666666666666666],
            delta_x = Float64[0.125, 0.08333333333333333],
            delta_y = Float64[0.02608695652173913, 0.013043478260869565],
            sigma = Float64[0.008695652173913044, 0.004347826086956522],
        ),
        expected_cost_per_target_payload = (
            gathered_cpt = Float64[0.043478260869565216, 0.06956521739130435],
            targets = Float64[0.0391304347826087, 0.0608695652173913],
            sigma = Float64[0.008695652173913044, 0.017391304347826087],
        ),
        expected_lift_log_density = -2.6131754993891394,
        expected_cost_per_target_log_density = -0.2499999999999999,
        expected_total_log_density = -2.8631754993891394,
    ),
]
