# Package entry points and shared public functions.
export epsilon_version
export fit!
export fit_transform!
export predict
export prior_predict
export summary_table
export transform

# Prior and distribution specifications.
export active_count
export deserialize_prior
export EpsilonPrior
export expand_masked_values
export FinnishHorseshoePrior
export finnish_horseshoe_coefficients
export HorseshoePrior
export horseshoe_coefficients
export instantiate_distribution
export LaplacePrior
export LogNormalPrior
export MaskedPrior
export R2D2Prior
export r2d2_coefficients
export r2d2_variance_weights
export regularized_local_scales
export Scaled
export SkewStudentT
export TimeVaryingMediaConfig

# Core model types, configuration, metadata, and validation.
export AbstractMMMModel
export AbstractModel
export AbstractRegressionModel
export build_model
export deserialize_model_config
export MMMData
export PanelMMMData
export ModelArtifactMetadata
export ModelConfig
export model_config_from_dict
export ModelConfigError
export ModelCoordinateMetadata
export ModelDiagnostics
export model_diagnostics
export ModelFitState
export MMMModelSpec
export ModelResults
export nobs
export normalize_channel_columns
export npanel_observations
export npanels
export ntime
export PanelAxis
export panel_axis
export panel_axes
export PanelCoordinate
export panel_coordinate
export panel_coordinates
export validate_channel_values
export validate_column_indices
export validate_mmm_data
export validate_model_config
export validate_panel_mmm_data
export validate_target_data

# Serialization and config IO.
export load_inference_results
export load_model
export load_model_config
export load_public_config
export load_results
export load_sampler_config
export save_inference_results
export save_model
export save_results

# Transforms and preprocessing.
export batched_convolution
export binomial_adstock
export centered_logistic_saturation
export ConvMode
export delayed_adstock
export fourier_features
export geometric_adstock
export hill_function
export inverse_transform
export logistic_saturation
export max_abs_scale_channel_data
export MaxAbsScaleChannels
export MaxAbsScaler
export max_abs_scale_target_data
export MaxAbsScaleTarget
export michaelis_menten
export standardize_control_data
export StandardizeControls
export StandardScaler
export tanh_saturation
export WeibullType
export weibull_adstock

# Calibration and lift-test helpers.
export assert_monotonic_lift
export build_cost_per_target_calibration_payload
export build_lift_test_calibration_payload
export CalibrationStepConfig
export cost_per_target_penalties
export cost_per_target_total_penalty
export CostPerTargetCalibrationPayload
export CostPerTargetCalibrationRows
export exact_row_indices
export gamma_shape_scale
export lift_test_estimated_lift
export lift_test_estimated_lift_ad
export lift_test_gamma_distribution
export lift_test_likelihood_terms
export lift_test_log_density
export lift_test_payload_log_density
export LiftTestCalibrationPayload
export LiftTestCalibrationRows
export MMMCalibrationSpec
export NonMonotonicError
export scale_channel_lift_measurements
export scale_lift_measurements
export scale_target_for_lift_measurements
export TimeSeriesCalibrationInput
export UnalignedValuesError
export validate_calibration_step_config
export validate_cost_per_target_calibration_payload
export validate_lift_test_calibration_payload
export validate_lift_test_columns

# Inference results, sampler configuration, and diagnostics.
export convergence_report
export convergence_warnings
export ConvergenceIssue
export ConvergenceReport
export ConvergenceWarning
export ConvergenceWarnings
export has_convergence_issues
export has_convergence_warnings
export has_numerical_errors
export has_sampler_warnings
export inference_results
export InferenceResults
export InferenceSampleStats
export ParameterDiagnostics
export SamplerConfig
export sampler_config_from_dict
export SamplerDiagnostics
export sampler_diagnostics
export SamplerWarning
export SamplerWarnings
export sampler_warnings
export validate_sampler_config

# MMM model surfaces.
export model_results
export PanelMMM
export TimeSeriesMMM

# Post-model result surfaces and summaries.
export adstock_curve_results
export AdstockCurveResults
export budget_audit_table
export budget_impact_table
export contribution_results
export ContributionResults
export decomposition_results
export DecompositionResults
export metric_results
export MetricResults
export response_curve_results
export ResponseCurveResults
export saturation_curve_results
export SaturationCurveResults

# Optimization and scenario planning.
export AbstractScenarioSpec
export assert_scenario_store_compatible
export BudgetOptimizationResult
export CurrentScenarioSpec
export evaluate_manual_scenario
export FixedBudgetOptimizedScenarioSpec
export load_scenario_store
export ManualAllocationScenarioSpec
export ManualScenarioEvaluationResult
export optimize_budget
export PanelBudgetOptimizationResult
export scenario_plan
export scenario_store_plan
export ScenarioDataArraySpec
export ScenarioPlanResult
export ScenarioStoreArtifact
export write_scenario_store

# Pipeline runtime.
export pipeline_main
export PipelineRunConfig
export PipelineRunResult
export PipelineStageRecord
export PipelineValidationResult
export run_pipeline

# Plotting.
export adstock_curve_plot
export budget_optimization_plot
export contribution_area_plot
export contribution_plot
export decomposition_plot
export epsilon_theme
export observed_fitted_plot
export posterior_density_plot
export prior_posterior_plot
export residual_diagnostics_plot
export response_curve_plot
export saturation_curve_plot
export trace_plot
export write_plot_bundle
