# Core distributions and prior specifications.
include("distributions/priors.jl")
include("distributions/special.jl")
include("distributions/masked.jl")
include("distributions/shrinkage.jl")

# Model data/config and MMM feature primitives used by builders.
include("model/types.jl")
include("model/config.jl")
include("mmm/seasonality.jl")
include("mmm/hsgp.jl")
include("mmm/trend.jl")
include("mmm/events.jl")
include("mmm/holidays.jl")
include("mmm/controls.jl")
include("mmm/calibration.jl")
include("model/builder.jl")
include("model/io.jl")

# Result envelopes, inference, fitted MMM model methods, and post-model output.
include("model/results.jl")
include("model/diagnostics.jl")
include("inference/mcmc.jl")
include("inference/diagnostics.jl")
include("inference/results.jl")
include("mmm/media.jl")
include("mmm/model.jl")
include("mmm/panel.jl")
include("postmodel/types.jl")
include("postmodel/replay.jl")
include("postmodel/contributions.jl")
include("postmodel/decomposition.jl")
include("postmodel/response_curves.jl")
include("postmodel/metrics.jl")
include("postmodel/summary.jl")

# Optimization, scenario planning, pipeline, and plotting surfaces.
include("optimization/types.jl")
include("model/coordinate_forwarders.jl")
include("optimization/constraints.jl")
include("optimization/objective.jl")
include("optimization/optimizer.jl")
include("optimization/panel.jl")
include("optimization/summary.jl")
include("scenario_planner.jl")
include("pipeline/config.jl")
include("pipeline/context.jl")
include("pipeline/stages.jl")
include("pipeline/run.jl")
include("pipeline/cli.jl")
include("plotting/theme.jl")
include("plotting/diagnostics.jl")
include("plotting/postmodel.jl")
include("plotting/optimization.jl")
include("plotting/bundle.jl")

# Existing load order is preserved exactly. Transforms remain here after
# plotting because Phase 57 documents the current order without reordering it.
include("transforms/convolution.jl")
include("transforms/adstock.jl")
include("transforms/saturation.jl")
include("transforms/scaling.jl")
